
variable "os_iso_path" {
  type    = string
  default = "[Your_Datastore] <your_path>.iso"
}

variable "vm-cpu-num" {
  type    = string
  default = "2"
}

variable "vm-disk-size" {
  type    = string
  default = "40960"
}

variable "vm-mem-size" {
  type    = string
  default = "4096"
}

variable "vm-name" {
  type    = string
  default = "<Your_VM_Name>"
}

variable "vsphere-cluster" {
  type    = string
  default = "CL_1"
}

variable "vsphere-datacenter" {
  type    = string
  default = "<Your_Datacenter>"
}

variable "vsphere-datastore" {
  type    = string
  default = "<Your_Datastore>"
}

variable "vsphere-folder" {
  type    = string
  default = "<Your_Folder>"
}

variable "vsphere-network" {
  type    = string
  default = "<Your_Network>"
}

variable "vsphere-password" {
  type    = string
  default = "<Your_Password>"
}

variable "vsphere-server" {
  type    = string
  default = "<Your_Server_IP_or_FQDN>"
}

variable "vsphere-user" {
  type    = string
  default = "<Your_User>"
}

variable "winadmin-password" {
  type    = string
  default = "<Your_WinRM_Password>"
}

variable "winrm_username" {
  type    = string
  default = "<Your_WinRM_User>"
}
variable "floppy_img_path"
  type    = string
  default = "[Your_Datastore] ISO/pvscsi_Windows8.flp"

source "vsphere-iso" "autogenerated_1" {
  CPUs                 = "${var.vm-cpu-num}"
  RAM                  = "${var.vm-mem-size}"
  RAM_reserve_all      = true
  cluster              = "${var.vsphere-cluster}"
  communicator         = "winrm"
  create_snapshot      = "true"
  datacenter           = "${var.vsphere-datacenter}"
  datastore            = "${var.vsphere-datastore}"
  disk_controller_type = ["pvscsi"]
  storage {
  disk_size             = "${var.vm-disk-size}"
  disk_thin_provisioned = true
  disk_controller_index = 0
  }
  firmware             = "efi"
  boot_order	       = "disk,cdrom"
  floppy_files         = ["./autounattend.xml", "./scripts/disable-network-discovery.cmd", "./scripts/enable-rdp.cmd", "./scripts/enable-winrm.ps1", "./scripts/install-vm-tools.cmd", "./scripts/set-temp.ps1", "./scripts/microsoft-updates.ps1", "./scripts/win-updates.ps1", "./scripts/choco.ps1", "./scripts/disable-screensaver.ps1"]
  floppy_img_path      = "${var.floppy_img_path}"
  folder               = "${var.vsphere-folder}"
  guest_os_type        = "windows9_64Guest"
  insecure_connection  = "true"
  iso_paths            = ["${var.os_iso_path}", "[] /vmimages/tools-isoimages/windows.iso"]
  network_adapters {
    network      = "${var.vsphere-network}"
    network_card = "vmxnet3"
  }
  password = "${var.vsphere-password}"
  
  username       = "${var.vsphere-user}"
  vcenter_server = "${var.vsphere-server}"
  vm_name        = "${var.vm-name}"
  winrm_insecure = "true"
  winrm_password = "${var.winadmin-password}"
  winrm_use_ssl  = "true"
  winrm_username = "${var.winrm_username}"
}

build {
  sources = ["source.vsphere-iso.autogenerated_1"]

  provisioner "windows-restart" {
  }

  provisioner "file" {
    destination = "c:\\temp\\build\\scripts\\windowsupdate.ps1"
    source      = "./scripts/windowsupdate.ps1"
  }

  provisioner "powershell" {
    scripts = ["./scripts/packer_windowsupdate.ps1"]
  }

  provisioner "windows-restart" {
    restart_timeout = "30m"
  }

  provisioner "powershell" {
    scripts = ["./scripts/choco.ps1"]
  }

}
